### ISSUE TITLE
Q: Show all WAITING, regardless of the date

### ISSUE THREAD

**Issue by abonhote** [alphapapa/org-super-agenda#39] opened 2018-06-05 15:45 UTC
Being pretty new to emacs I didn't get this to work. I tried things like

``
(:name "WAITING"
  :and ( :todo "WAITING" :date nil ))
``

What I would like to have is a list of WAITING tasks which have or don't have a due date.

Any help highly appreciated!

Cheers

André

**Comment by alphapapa** [comment] 2018-06-05 16:49
Hi André,

If you don't care whether they have a due date, then leave off the `:date nil` part.  Just use:

`(:todo "WAITING")`

That will match any "WAITING" item and the group will be named automatically.

BTW, for due dates specifically (i.e. "DEADLINE" in Org), use the `:deadline` selector.

**Comment by abonhote** [comment] 2018-06-06 11:20
Hi Alphapapa

Thanks - Hm ... I tried that, it only displays items which are WAITING on the specific day.

My whole config looks like this, with the "Roggwil" part being relevant. 

```lisp
(setq org-agenda-custom-commands
	'(("c" "Simple agenda view"
	   ((tags "PRIORITY=\"A\""
		  ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
		   (org-agenda-overriding-header "High-priority unfinished tasks:")))
	    (agenda "")
	    (alltodo "")))
	  ("r" "Roggwil-Tasks" agenda
	   (org-super-agenda-mode)
	   (
	    (org-agenda-span 2)
	    (org-super-agenda-groups
	     '((:log t)
	       (:name "Roggwil"
		      :tag "roggwil")
	       (:name "WAITING"
		      :todo "WAITING"
		      :order 98))
	     ))
	   (org-agenda-list)
	   )
	  ("A" "Super-Agenda" agenda
	   (org-super-agenda-mode)
	   (
	    (org-agenda-span 2)
	    (org-super-agenda-groups
	     '((:log t)  ; Automatically named "Log"
               (:name "Schedule"
                      :time-grid t)
               (:name "Today"
                      :scheduled today)
               (:name "Due today"
                      :deadline today)
               (:name "Overdue"
                      :deadline past)
               (:name "Due soon"
                      :deadline future)
               (:name "Unimportant"
                      :todo ("SOMEDAY" "MAYBE" "CHECK" "TO-READ" "TO-WATCH")
                      :order 100)
               (:name "Waiting..."
                      :todo "WAITING"
                      :order 98)
               (:name "Scheduled earlier"
                      :scheduled past))))
	   (org-agenda-list)
	   )
	  ("u" "UPC" agenda "upc" ((org-agenda-files (file-expand-wildcards (concat org-directory "/upc.org")))))))
```

This (C-c a r) shows me today's tasks tagged with "roggwil", today's "WAITING" taks, today's "Other items" (which is `org-agenda-list`) and tomorrow's "Other Items".

Lisp has far too many brackets for my brain - freaking out ;)

Cheers

André

**Comment by alphapapa** [comment] 2018-06-06 22:54
>  it only displays items which are WAITING on the specific day.

That's what the Org Agenda does.  If you want a list of all tasks regardless of time, you should use a different command, like `org-todo-list`.

**Comment by abonhote** [comment] 2018-06-07 06:59
Darn, I really need to get through that bloody lisp tutorial one day. Removing the ``(org-super-agenda-mode)`` tells me that `` (org-agenda-span 2)`` is wrong...

Never mind, you pointed me in the right direction. Thanks a lot for answering these basic questions.

**Comment by alphapapa** [comment] 2018-06-07 07:14
Well, the structure of the `org-agenda-custom-commands` variable can be a bit confusing.  You can bring up the documentation with `C-h v org-agenda-custom-commands RET`.  I think the key is this part:

The problem is that `(org-super-agenda-mode)` was taking up the `match` spot.  Try replacing it with an empty string, `""`, and I think it will work then.

**Comment by alphapapa** [comment] 2018-06-20 22:31
Going to close this now, but feel free to reply.

**Closed by alphapapa** 2018-06-20 22:31 UTC

**Comment by lhindir** [comment] 2019-09-18 17:43
So if I understand correctly, items matched by only keyword still have to have a timestamp that would cause them to show up on the day? So to get items to actually show up in the "Waiting" group, you would need to schedule them for the day?

**Comment by alphapapa** [comment] 2019-09-18 20:33
@lhindir Your question relates not to `org-super-agenda` but to Org Agenda.  This package does not select items to be displayed, it only groups the ones that are selected by Org Agenda (or `org-ql`, if you're using it).
